### ISSUE TITLE
Geo.postal_code - short is too "short"...

### ISSUE THREAD

**Issue by aobszyns** [shadow-box/Palo-Alto-Networks-ELK-Stack#5]
SourceIPGeo.postal_code defined as "short" is too small:

This filling up logstash.log for many postal codes:

[2018-02-25T23:52:27,527][WARN ][logstash.outputs.elasticsearch] Could not index event to Elasticsearch. {:status=>400, :action=>["index", {:_id=>nil, :_index=>"traffic", :_type=>"doc", :_routing=>nil}, #<LogStash::Event:0x5e4cb72e>], :response=>{"index"=>{"_index"=>"traffic", "_type"=>"doc", "_id"=>"ks5xxxxBLcDxxxxxx_", "status"=>400, "error"=>{"type"=>"mapper_parsing_exception", "reason"=>"failed to parse [DestinationIPGeo.postal_code.keyword]", "caused_by"=>{"type"=>"illegal_argument_exception", "reason"=>"**Value [95111] is out of range for a short"**}}}}}

**Comment by shadow-box** [comment]
Hello! Thanks for pointing this out; in fact I noticed two issues. First the dma_code field mapping was inconsistent across Src & Dst IPGeo. The postal_code 'short' field value didn't account for Postal Codes above 32,767. This now correctly mapped to 'integer'. Both issues have been corrected and pushed to both traffic and threat templates.

**Comment by aobszyns** [comment]
There was also PCAP_ID which is too short for 8.0++ PAN-OS
Should be double I think. I cannot provide sample of error output today but will try another day.

Also sometimes string parsing was complaining about postal codes (keyword) while some countires uses version with dash (-). It looks like 12345 and 12-345 have to be supported.

**Comment by gitthismoney** [comment]
If it's set to integer then canadian postal codes won't index... ie V5T

**Comment by shadow-box** [comment]
You are absolutely correct; showing my data ethocentrism here. I'll correct and update shortly...

**Comment by earcuri** [comment]
@shadow-box @aobszyns 
Because of the limitations of both postal-code and possibly PCAP, I am thinking they should both be strings.  That is, unless, you are trying to do math with either of them.

**Comment by shadow-box** [comment]
@aobszyns @sdndude 
It's been a while since I touched this. I modified the postal_code type to "text" so partial matching will work and modified the PCAP_ID to a "long" (64-bit integer); figured this might be friendlier long term than "text". Thoughts?

**Comment by earcuri** [comment]
@shadow-box @aobszyns 
That is exactly what I did with safe-networking and was going to do the same here when I was done testing.  I have had no issues with it, though I am forcing the PCAP using script generated values, not actual PCAP ids from the NGFW (all of the data is generated actually).  I don't think that should matter in this case though.  Postal code is 'text' and PCAP_ID is 'long' in my testing and they work fine.

**Comment by shadow-box** [comment]
@sdndude the datatype of 'long' works perfect, example PCAP_ID record:
# PCAP_ID  - 1,204,300,927,259,901,952
I couldn't imagine a generated ID would eclipse a 64-bit integer. 

@aobszyns the 'text' datatype clears out the errors on GeoIP postal_code as expected:
t DestinationIPGeo.postal_code - J6N

Closing this issue...
