### ISSUE TITLE
Meaning GEOIP field in the mutate section

### ISSUE THREAD

**Issue by tfanabe** [shadow-box/Palo-Alto-Networks-ELK-Stack#6]
Good morning,
I would like to know the menaing of GeoIP field in the mutate section, because I don't find this field in the traffic of threat log (obviously) and in the .json files there aren't this field.

Any suggestions?

Thanking in advance

Giuliano

**Comment by earcuri** [comment]
The GeoIP fields are populated by logstash by doing a geoip lookup on the src and dst IPs in the log message.  This describes it more in detail: https://www.elastic.co/guide/en/logstash/current/plugins-filters-geoip.html

If you are not getting them, then that means that your src and dst addresses are all RFC1918 addresses.  They are filtered out with the following line (for src as an example) in the .conf file:
```
if [SourceIP] and [SourceIP] !~ "(^127\.0\.0\.1)|(^10\.)|(^172\.1[6-9]\.)|(^172\.2[0-9]\.)|(^172\.3[0-1]\.)|(^192\.168\.)|(^169\.254\.)" 
```

However, if you aren't getting them and you do not have RFC1918 addresses for everything, then we need to troubleshoot it more.

**Comment by shadow-box** [comment]
Thanks @sdndude for reminding me I had open issues to attend to. 👍
