### ISSUE TITLE
Index patterns for saved objects 

### ISSUE THREAD

**Issue by ghost** [shadow-box/Palo-Alto-Networks-ELK-Stack#8]
I followed the guide and it does not seem to have the index patterns for the saved objects. Did I miss them or something? I created some, but they don't seem to link to the saved objects.

**Comment by CoyoteKG** [comment]
I also have this problem when I tried to import visualization from "Visualizations-Export.json"
getting error 
![image](https://user-images.githubusercontent.com/17199551/54134672-afbfd780-4418-11e9-83be-a73dddf37071.png)

**Comment by shadow-box** [comment]
@wikedeye & @CoyoteKG : The provided JSON templates establish the formatting structure, you must create the Indexes based upon the templates with the time filter of @timestamp. You can follow this guide here to create the index patterns:
https://www.elastic.co/guide/en/kibana/current/tutorial-define-index.html

In the end you will end up with a configuration like this:
![Screen Shot](https://user-images.githubusercontent.com/3009267/54138281-88a3de80-43f5-11e9-9d2c-09765d113920.png)

**Comment by CoyoteKG** [comment]
@shadow-box thanks for quick response.
I already created indexes for traffic

![image](https://user-images.githubusercontent.com/17199551/54182374-a3339180-44a1-11e9-997f-d009c113be64.png)

More details about setup,
Paloalto is version 8.1
ELK 6.6.1

**Comment by shadow-box** [comment]
@CoyoteKG Have you followed the prompts to associate the Visualization with the traffic index you have created? You choose the index pattern in the column labeled 'New index pattern'.

**Comment by ghost** [comment]
My issue ended up being that I commented out the main pipeline that fed the data to logstash.  I was installing another project and followed the direction without realizing what it would do.
